-- Criar tabela 'sales_estrela' para o sistema de entregas

CREATE TABLE IF NOT EXISTS sales_estrela (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Dados do Produto/Venda
    product_category TEXT, -- 'iphone' ou 'acessorios'
    product_name TEXT, -- Nome do produto (ex: iPhone 13 128GB)
    total_value NUMERIC, -- Valor total
    payment_method TEXT, -- 'credit', 'pix', 'cash', 'link'
    payment_details TEXT, -- '12x de R$ 100,00'
    
    -- Dados do Cliente
    customer_name TEXT,
    customer_phone TEXT,
    
    -- Dados de Entrega
    is_delivery BOOLEAN DEFAULT TRUE,
    delivery_status TEXT CHECK (delivery_status IN ('pending', 'ready', 'shipping', 'delivered', 'cancelled')) DEFAULT 'pending',
    delivery_address TEXT,
    delivery_reference_point TEXT,
    
    -- Controle Interno
    salesperson_name TEXT, -- Nome do vendedor
    notes TEXT, -- Observações gerais
    completed_at TIMESTAMPTZ -- Quando foi entregue/finalizado
);

-- Comentários para documentação
COMMENT ON TABLE sales_estrela IS 'Tabela dedicada para gestão de entregas e vendas da Estrela iPhones';
COMMENT ON COLUMN sales_estrela.delivery_status IS 'Status: pending (Pendente), ready (Pronto), shipping (Em Rota), delivered (Entregue), cancelled (Cancelado)';
